services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mired

  ms_main_app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      FLASK_ENV: development
      DATABASE_DEV_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_dev_db
      DATABASE_TEST_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_test_db
      DATABASE_PROD_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_prod_db
      MS_CATALOGO_URL: http://ms_catalogo:5000
      MS_STOCK_URL: http://ms_stock:5000
      MS_PAGO_URL: http://ms_pago:5000
      MS_COMPRAS_URL: http://ms_compras:5000
      REDIS_URL: redis://redis:6379
    networks:
      - mired

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: main_app_user
      POSTGRES_PASSWORD: main_app_password
      POSTGRES_DB: main_app_db
    ports:
      - "5433:5432"
    networks:
      - mired
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql # Montar el archivo de inicialización
  ms_catalogo:
    container_name: ms_catalogo
    build:
      context: ../microservicio-catalogo # Ruta hacia el microservicio
    ports:
      - "5003:5000"
    environment:
      FLASK_ENV: development
      DATABASE_DEV_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_dev_db
      DATABASE_TEST_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_test_db
      DATABASE_PROD_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_prod_db
      SQLALCHEMY_ENGINE_OPTIONS: |
        {"connect_args": {"options": "-csearch_path=catalogo_schema"}}
      REDIS_URL: redis://redis:6379
    networks:
      - mired
  ms_stock:
    container_name: ms_stock
    build:
      context: ../ms-inventarios # Ruta hacia el microservicio
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_DEV_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_dev_db
      DATABASE_TEST_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_test_db
      DATABASE_PROD_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_prod_db
      SQLALCHEMY_ENGINE_OPTIONS: |
        {"connect_args": {"options": "-csearch_path=stock_schema"}}
      REDIS_URL: redis://redis:6379
    networks:
      - mired

  ms_pago:
    container_name: ms_pago
    build:
      context: ../ms-pago # Ruta hacia el microservicio
    ports:
      - "5002:5000"
    environment:
      FLASK_ENV: development
      DATABASE_DEV_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_dev_db
      DATABASE_TEST_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_test_db
      DATABASE_PROD_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_prod_db
      SQLALCHEMY_ENGINE_OPTIONS: |
        {"connect_args": {"options": "-csearch_path=pago_schema"}}
      REDIS_URL: redis://redis:6379
    networks:
      - mired

  ms_compras:
    container_name: ms_compras
    build:
      context: ../ms-compras # Ruta hacia el microservicio
    ports:
      - "5001:5000"
    environment:
      FLASK_ENV: development
      DATABASE_DEV_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_dev_db
      DATABASE_TEST_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_test_db
      DATABASE_PROD_URL: postgresql+psycopg2://main_app_user:main_app_password@db:5432/main_app_prod_db
      SQLALCHEMY_ENGINE_OPTIONS: |
        {"connect_args": {"options": "-csearch_path=compras_schema"}}
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      REDIS_DB: '0'
      REDIS_PASSWORD: ''
    networks:
      - mired

volumes:
  postgres_data:


networks:
  mired:
    driver: bridge
