api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

entryPoints:
  http:
    address: :80
  traefik:
    address: :8080

volumes:
  - ./acme.json:/acme.json
